version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "square-python"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1k6jegprjnmi4"
s3_prefix = "square-python"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["HelloWorldFunction=262927611093.dkr.ecr.ap-northeast-1.amazonaws.com/squarepython897fb4b6/helloworldfunction19d43fc4repo"]
